name: Increment Version

on:
  workflow_dispatch:

  # https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
    inputs:
      version:
        description: "Current version"
        required: true
        type: string
      TAG:
        description: 'Test scenario tags'
        required: true
        type: string
      CONTENT_BUCKET:
        type: choice
        description: nonprod -  assembly, data-migration, functional, integration and performance
        options:
        - lab
        - assembly
        - funct
        - integ
        - migrate
        - perf
        - uat
        - stage
        - prod2
        
jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Show Input Selection
        run: |
          echo "Version: ${{ inputs.version }}"
          echo "Input Tag: ${{ inputs.TAG }}"          
          echo "CONTENT_BUCKET: ${{ inputs.CONTENT_BUCKET }}"



      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Run Version Increment Script
        id: increment_version
        run: |
          updated_version=$(python scripts/incrementVersionNumber.py ${{ github.event.inputs.version }} )
          echo "UPDATED_VERSION=${updated_version}" >> $GITHUB_ENV

      - name: Use Updated Version
        run: |
          echo "New version is $UPDATED_VERSION"
